# Generated by Django 5.0.1 on 2024-01-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/gallery/images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
