# Generated by Django 5.0.1 on 2024-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0003_galleryimage_aos_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('imagen_usuario', models.ImageField(upload_to='static/testimonios/images/')),
            ],
        ),
    ]
