# Generated by Django 4.2.7 on 2024-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0006_canton_lugar_hospedaje_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedaje',
            name='fotoHospedaje',
            field=models.ImageField(null=True, upload_to='static/hospedajes/images'),
        ),
    ]
