# Generated by Django 4.2.7 on 2024-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0007_alter_hospedaje_fotohospedaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='horario',
        ),
        migrations.AddField(
            model_name='lugar',
            name='hora_abre',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='hora_cierre',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='fotolugar',
            field=models.ImageField(null=True, upload_to='static/lugar/images'),
        ),
    ]
