# Generated by Django 4.2.7 on 2024-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0008_remove_lugar_horario_lugar_hora_abre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='infoLugar',
            field=models.TextField(max_length=225, null=True),
        ),
    ]
