# Generated by Django 4.2.7 on 2024-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VivaCityApp', '0011_alter_agenda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['user'], 'verbose_name': 'agendas', 'verbose_name_plural': 'agendas'},
        ),
    ]
